[[headers]]
  for = "/test/*"
  [headers.values]
    cache-control = '''
    max-age=7200,
    public'''

[[headers]]
  for = "/img/*"
  [headers.values]
    cache-control = '''
    max-age=7200,
    public'''

